source 'https://rubygems.org'

gem 'rake'
gem 'ProMotion'
gem 'motion_print'
gem 'sugarcube', require: 'sugarcube-all'
gem 'ProMotion-menu'
gem 'ProMotion-map'
gem 'bubble-wrap'
gem 'motion-kit'
gem 'ProMotion-form'
gem 'motion_record'
gem 'motion-sqlite3'
gem "motion.h", :git => "https://github.com/kastiglione/motion.h"